- hosts: all
  connection: httpapi
  collections:
    - fortinet.fortinet.fortios
  vars:
    vdom: "root"
    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: no
    ansible_httpapi_port: 443
  tasks:
  - name: Configure IPv4 addresses
    fortios_firewall_address:
      vdom:  "{{ vdom }}"
      state: "present"
      firewall_address:
        name: " new_test123"
        type: "ipmask"
        subnet: "99.99.99.0 255.255.255.0"
        visibility: "enable"
