- hosts: all
  connection: httpapi

  vars:
    vdom: "root"
    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: no
    ansible_httpapi_port: 443
  tasks:
  - name: Configure IPv4 addresses
    fortios_firewall_address:
      vdom:  "{{ vdom }}"
      state: "present"
      firewall_address:
        name: "{{ new_add_name }}"
        type: "ipmask"
        subnet: "{{ new_add_subnet }}"
        visibility: "enable"
