- hosts: fortimanagers
  collections:
    - fortinet.fortimanager
  connection: httpapi
  vars:
     ansible_httpapi_use_ssl: True
     ansible_httpapi_validate_certs: False
     ansible_httpapi_port: 443
  tasks:

    - name: make SDWAN template
      fmgr_generic:
        method: set
        params:
          - url: '/pm/wanprof/adom/{{adom}}'
            data:
              - name: '{{sdwan_tpt}}'
                type: wanprof
                
    - name: add WAN1
      fmgr_generic:
        method: add
        params:
          - url:  '/pm/config/adom/{{adom}}/obj/dynamic/virtual-wan-link/members'
            data:
              - name: wan1
                comment: null
                interface: wan1
                cost: 0
                weight: 1
                volume-ratio: 1
                dynamic_mapping: null
                ingress-spillover-threshold: 0
                priority: 0
                source: 0.0.0.0
                spillover-threshold: 0
                status: 1
