- hosts: fortimanagers
  collections:
    - fortinet.fortimanager
  connection: httpapi
  vars:
     ansible_httpapi_use_ssl: True
     ansible_httpapi_validate_certs: False
     ansible_httpapi_port: 443
  tasks:

    - name: add WAN1
      fmgr_generic:
        method: add
        params:
          - url:  '/pm/config/adom/{{adom}}/obj/dynamic/virtual-wan-link/members'
            data:
              - name: wan1
                interface: wan1

