- hosts: fortimanagers
  collections:
    - fortinet.fortimanager
  connection: httpapi
  vars:
     ansible_httpapi_use_ssl: True
     ansible_httpapi_validate_certs: False
     ansible_httpapi_port: 443
  tasks:

    - name: del device {{adom}} / {{fgt}}
      fmgr_generic:
        method: exec
        params:
          - url: '/dvm/cmd/del/device'
            data:
              adom: '{{adom}}'
              device: '{{fgt}}'
      ignore_errors: yes

    - name: del adom {{adom}}
      fmgr_generic:
        method: delete
        params:
          - url: '/dvmdb/adom/{{adom}}'
      ignore_errors: yes

