- name: 'Acme ZTP demo: undo setup: delete device, delete adom'
  hosts: all
  gather_facts: no
  connection: httpapi
  collections:
    - fortinet.fortimanager
  vars:
    #ansible_httpapi_use_ssl: True
    #ansible_httpapi_validate_certs: False
    #ansible_httpapi_port: 10406

    # .:hosts.yml tower:project
    #adom: 'Subway'
    fgt:  '{{site_id}}'

  tasks:

    - name: del device {{adom}} / {{fgt}}
      fmgr_generic:
        method: exec
        params:
          - url: '/dvm/cmd/del/device'
            data:
              adom: '{{adom}}'
              device: '{{fgt}}'
      ignore_errors: yes

    - name: del adom {{adom}}
      fmgr_generic:
        method: delete
        params:
          - url: '/dvmdb/adom/{{adom}}'
      ignore_errors: yes

